version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker
    volumes:
    - ./:/var/www
    container_name: web
    ports:
    - "8888:80"
    links:
    - app
  app:
    build:
      context: ./
      dockerfile: .docker/app.docker
    container_name: app
    volumes:
    - ./:/var/www
    environment:
    - NODE_ENV=production