version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.docker
    container_name: web
    volumes:
    - static-content:/var/www/public
    depends_on:
    - app
    ports:
    - "8888:80"
    links:
    - app
  app:
    build:
      context: ./
      dockerfile: .docker/app.docker
    container_name: app
    volumes:
    - static-content:/var/www/public
    environment:
    - APP_ENV=production
volumes:
  static-content: